require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'BibleStudyCompanion' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'BibleStudyCompanionTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  use_flipper!({
    'Flipper' => '0.54.0',
    'Flipper-RSocket' => '1.1',
    'Flipper-Folly' => '2.3.0'
  })
  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'BibleStudyCompanion-tvOS' do
  # Pods for BibleStudyCompanion-tvOS

  target 'BibleStudyCompanion-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end